import { defineConfig, loadEnv } from "vite";

export default defineConfig({
    // base: "/",
    // clearScreen: true,
    envPrefix: "VITE_", // can be "APP_"
    // Where to read env files
    envDir: ".",
    logLevel: "info",
    server: {
        port: 3000,
        // just open the app in the browser
        // or open specific path ("/foods/1")
        open: true,
        // if port 3000 is not available so
        // DO NOT search for the next port and just
        // halt the application
        strictPort: true,
    },
    preview: {
        port: 8080,
    },
    css: {
        // with source map basically the browser can map
        // css generated by a pre-processor (such as sass) back to
        // the source file, It means we will able to trace
        // that specifc property back to it's scss file
        devSourcemap: true,
    },
});

// // this callback function can be an async function
// export default defineConfig(({ command, mode, ssrBuild }) => {
//     // serve development false (npm run dev)
//     // build production false  (npm run build)
//     // serve production flase  (npm run preview)
//     console.log(command, mode, ssrBuild);

//     if (mode === "production") {
//         return { base: "/vite/" };
//     }

//     return {};
// });

// export default defineConfig(({ command, mode }) => {
//     const env = loadEnv(mode, process.cwd(), "VITE_");

//     console.log(env);

//     return {};
// });
